apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sentinelx-hpa
  namespace: sentinelx
  labels:
    app: sentinelx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sentinelx-app
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
